name: mr_ms_luna_controller
description: "A premium Flutter controller for Mr.&Ms Luna Smart Toy Robot."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.19.6
  google_sign_in: ^6.2.1
  flutter_blue_plus: ^1.31.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  audioplayers: ^6.0.0
  google_fonts: ^6.1.0
  file_picker: ^8.0.0
  provider: ^6.1.1
  http: ^1.2.0
  gif: ^2.2.3
  permission_handler: ^11.3.1
  record: ^6.0.0
  flutter_pcm_sound: ^3.3.3
  qr_flutter: ^4.1.0
  url_launcher: ^6.2.5
  share_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/logo.png
