/**
 * Luna Display Studio - C++ Code Generator for ESP32-S3 1.69" Display
 * Outputs production-ready TFT_eSPI / Arduino code matching 1.69 Luna Firmware
 */

const CodeGenerator = {
  /**
   * Convert standard #RRGGBB hex string to 16-bit RGB565 hex string (0xXXXX)
   */
  hexToRGB565(hex) {
    if (!hex) return "0xFFFF";
    if (hex.startsWith("rgba")) {
      const m = hex.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
      if (m) {
        const r = parseInt(m[1]), g = parseInt(m[2]), b = parseInt(m[3]);
        const val = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
        return "0x" + val.toString(16).toUpperCase().padStart(4, "0");
      }
    }
    const cleanHex = hex.replace("#", "").substring(0, 6);
    const num = parseInt(cleanHex, 16);
    if (isNaN(num)) return "0xFFFF";
    const r = (num >> 16) & 255;
    const g = (num >> 8) & 255;
    const b = num & 255;
    const rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3);
    return "0x" + rgb565.toString(16).toUpperCase().padStart(4, "0");
  },

  /**
   * Generate Arduino / TFT_eSPI C++ function
   */
  generateArduinoCode(elements, screenBg = "#0b0f19") {
    const bgRGB = this.hexToRGB565(screenBg);
    let lines = [];
    lines.push("// ==========================================================================");
    lines.push("// Generated by Luna Display Studio for ESP32-S3 1.69\" (240x280 ST7789)");
    lines.push("// Includes Uiverse.io UI Components & Galaxy Library elements");
    lines.push("// ==========================================================================");
    lines.push("#include <TFT_eSPI.h>");
    lines.push('#include "luna_ui_elements.h"');
    lines.push("");
    lines.push("extern TFT_eSPI tft; // Reference to existing TFT instance");
    lines.push("");
    lines.push("void drawGeneratedScreen() {");
    lines.push(`  // 1. Clear background (${screenBg})`);
    lines.push(`  tft.fillScreen(${bgRGB});`);
    lines.push("");

    elements.forEach((el, index) => {
      const p = el.props;
      lines.push(`  // ── Element ${index + 1}: ${el.type} (${el.name}) ──`);

      switch (el.type) {
        // ── CARDS ──
        case "card_transaction": {
          const bg = this.hexToRGB565(p.bgColor);
          const iconBg = this.hexToRGB565(p.iconBg);
          const border = this.hexToRGB565(p.borderColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawTransactionCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${border}, ${iconBg}, "${p.title}", ${text});`);
          break;
        }

        case "dialog_order_valid": {
          const bg = this.hexToRGB565(p.bgColor);
          const accent = this.hexToRGB565(p.accentColor);
          const text = this.hexToRGB565(p.textColor);
          const sub = this.hexToRGB565(p.subtextColor);
          lines.push(`  drawOrderValidatedCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${accent}, "${p.title}", "${p.subtitle}", ${text}, ${sub});`);
          break;
        }

        case "uiverse_push_card": {
          const bg = this.hexToRGB565(p.bgColor);
          const bell = this.hexToRGB565(p.bellColor);
          const text = this.hexToRGB565(p.textColor);
          const sub = this.hexToRGB565(p.subtextColor);
          lines.push(`  drawPushCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${bell}, "${p.title}", "${p.subtitle}", ${text}, ${sub});`);
          break;
        }

        case "uiverse_weather_card": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          const sub = this.hexToRGB565(p.subtextColor);
          const accent = this.hexToRGB565(p.accentColor);
          lines.push(`  drawWeatherCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, "${p.city}", "${p.temp}", "${p.condition}", ${accent}, ${text}, ${sub});`);
          break;
        }

        case "uiverse_music_card": {
          const bg = this.hexToRGB565(p.bgColor);
          const accent = this.hexToRGB565(p.accentColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawMusicCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, "${p.track}", "${p.artist}", ${p.progress}, ${accent}, ${text});`);
          break;
        }

        case "uiverse_profile_card": {
          const bg = this.hexToRGB565(p.bgColor);
          const accent = this.hexToRGB565(p.accentColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawProfileCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, "${p.username}", "${p.rank}", "${p.level}", ${accent}, ${text});`);
          break;
        }

        case "card_glass": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const text = this.hexToRGB565(p.textColor);
          const sub = this.hexToRGB565(p.subtextColor);
          lines.push(`  drawGlassCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${border}, "${p.title}", "${p.subtitle}", ${text}, ${sub});`);
          break;
        }

        case "card_stat": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const accent = this.hexToRGB565(p.accentColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawStatCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${border}, "${p.label}", "${p.value}", "${p.unit}", ${accent}, ${text});`);
          break;
        }

        case "card_retro": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawRetroArcadeBox(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${bg}, ${border}, "${p.title}", "${p.score}", ${text});`);
          break;
        }

        // ── BUTTONS (EXACT UIVERSE) ──
        case "adamgiebl_plastic_parrot":
        case "uiverse_download_btn": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawDownloadButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, 20, ${bg}, "${p.label}", ${text});`);
          break;
        }

        case "sarthak_hungry_penguin": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawCTAButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, 10, ${bg}, "${p.label}", ${text});`);
          break;
        }

        case "gharsh_ancient_elephant": {
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawNeonBorderButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, 8, "${p.label}", ${text});`);
          break;
        }

        case "adamgiebl_fluffy_liger": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawFlowButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, 10, ${bg}, "${p.label}", ${text});`);
          break;
        }

        case "adamgiebl_lucky_donkey": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawNeumorphicButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, 8, ${bg}, "${p.label}", ${text});`);
          break;
        }

        case "vinod_afraid_falcon": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawScrollTopButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${bg}, "${p.label}", ${text});`);
          break;
        }

        case "btn_happy_coding": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawHappyCodingButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius || 12}, ${bg}, ${border}, "${p.label}", ${text});`);
          break;
        }

        case "btn_get_started": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawGetStartedButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, 10, ${bg}, "${p.label}", "${p.badge || 'G'}", ${text});`);
          break;
        }

        case "button_retro": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawRetroButton(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${bg}, ${border}, "${p.label}", ${text});`);
          break;
        }

        // ── TOGGLES (EXACT UIVERSE) ──
        case "adamgiebl_grumpy_moth":
        case "uiverse_ios_switch": {
          const active = this.hexToRGB565(p.activeColor || "#10b981");
          const inactive = this.hexToRGB565(p.inactiveColor || "#cbd5e1");
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawIOSSwitch(${p.x}, ${p.y}, ${p.w}, ${p.h}, "${p.label}", ${p.checked ? "true" : "false"}, ${active}, ${inactive}, ${text});`);
          break;
        }

        case "vinod_speaker_switch":
        case "uiverse_speaker_mute": {
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawSpeakerSwitch(${p.x}, ${p.y}, ${p.w}, ${p.h}, "${p.label}", ${p.checked ? "true" : "false"}, ${text});`);
          break;
        }

        case "uiverse_sun_moon": {
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawSunMoonSwitch(${p.x}, ${p.y}, ${p.w}, ${p.h}, "${p.label}", ${p.checked ? "true" : "false"}, ${text});`);
          break;
        }

        case "action_dock": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const iconCol = this.hexToRGB565(p.iconColor);
          lines.push(`  drawActionDock(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius || 10}, ${bg}, ${border}, ${iconCol});`);
          break;
        }

        // ── LOADERS (EXACT UIVERSE) ──
        case "alexruix_big_octopus": {
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawDotLoader(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${text});`);
          break;
        }

        case "shoh_ancient_lionfish":
        case "uiverse_coin_flip": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawCoinLoader(${p.x}, ${p.y}, ${p.w}, "$", ${bg}, ${text});`);
          break;
        }

        case "uiverse_orbit_loader": {
          const col = this.hexToRGB565(p.color);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawOrbitLoader(${p.x}, ${p.y}, ${p.w}, ${p.h}, "${p.label || 'LOADING'}", ${col}, ${text});`);
          break;
        }

        // ── CHECKBOXES (EXACT UIVERSE) ──
        case "adamgiebl_new_dingo":
        case "uiverse_neu_checkbox": {
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawNeumorphicCheckbox(${p.x}, ${p.y}, "${p.label || 'Checkbox'}", ${p.checked ? "true" : "false"}, ${text});`);
          break;
        }

        case "uiverse_radio_pill": {
          const accent = this.hexToRGB565(p.accentColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawRadioPill(${p.x}, ${p.y}, "${p.label}", ${p.selected ? "true" : "false"}, ${accent}, ${text});`);
          break;
        }

        case "checkbox": {
          const color = this.hexToRGB565(p.color);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawCheckbox(${p.x}, ${p.y}, "${p.label}", ${p.checked ? "true" : "false"}, ${color}, ${text});`);
          break;
        }

        // ── NOTIFICATIONS ──
        case "uiverse_level_up": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawLevelUpToast(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, "${p.player}", "${p.level}", ${text});`);
          break;
        }

        case "uiverse_star_toast": {
          const bg = this.hexToRGB565(p.bgColor);
          const star = this.hexToRGB565(p.starColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawStarToast(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, "${p.title}", "${p.subtitle}", ${star}, ${text});`);
          break;
        }

        case "card_notification": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const badge = this.hexToRGB565(p.badgeColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawNotificationCard(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${border}, "${p.sender}", "${p.title}", "${p.message}", "${p.time}", ${badge}, ${text});`);
          break;
        }

        // ── INPUTS ──
        case "uiverse_neu_input": {
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawNeumorphicInput(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, "${p.placeholder}", ${text});`);
          break;
        }

        case "uiverse_cyber_search": {
          const bg = this.hexToRGB565(p.bgColor);
          const border = this.hexToRGB565(p.borderColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawCyberSearch(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${bg}, ${border}, "${p.placeholder}", ${text});`);
          break;
        }

        // ── GAUGES ──
        case "progress_bar": {
          const fill = this.hexToRGB565(p.fillColor);
          const bg = this.hexToRGB565(p.bgColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawProgressBar(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${p.radius}, ${p.value}, "${p.label}", ${fill}, ${bg}, ${text});`);
          break;
        }

        case "progress_ring": {
          const arc = this.hexToRGB565(p.arcColor);
          const track = this.hexToRGB565(p.trackColor);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawRadialDial(${p.x}, ${p.y}, ${p.w}, ${p.value}, "${p.label}", "${p.time}", ${arc}, ${track}, ${text});`);
          break;
        }

        case "battery_gauge": {
          const col = this.hexToRGB565(p.color);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawBatteryGauge(${p.x}, ${p.y}, ${p.percent}, ${p.isCharging ? "true" : "false"}, ${col}, ${text});`);
          break;
        }

        case "audio_waveform": {
          const barCol = this.hexToRGB565(p.barColor);
          const bgCol = this.hexToRGB565(p.bgColor);
          lines.push(`  drawAudioWaveform(${p.x}, ${p.y}, ${p.w}, ${p.h}, ${barCol}, ${bgCol});`);
          break;
        }

        // ── TYPOGRAPHY ──
        case "digital_clock": {
          const col = this.hexToRGB565(p.color);
          const dateCol = this.hexToRGB565(p.dateColor);
          lines.push(`  drawDigitalClock(${p.x}, ${p.y}, "${p.time}", "${p.seconds}", "${p.date}", ${col}, ${dateCol});`);
          break;
        }

        case "status_badge": {
          const col = this.hexToRGB565(p.color);
          const text = this.hexToRGB565(p.textColor);
          lines.push(`  drawStatusBadge(${p.x}, ${p.y}, ${p.w}, ${p.h}, "${p.text}", ${col}, ${text});`);
          break;
        }

        case "label_text": {
          const col = this.hexToRGB565(p.color);
          lines.push(`  tft.setTextColor(${col});`);
          lines.push(`  tft.setTextDatum(MC_DATUM);`);
          lines.push(`  tft.drawString("${p.text}", ${p.x + p.w / 2}, ${p.y + p.h / 2}, 2);`);
          break;
        }

        default: {
          // Fallback generic Galaxy element
          const bg = this.hexToRGB565(p.bgColor || "#1e293b");
          const text = this.hexToRGB565(p.textColor || "#ffffff");
          lines.push(`  // Galaxy Element: ${el.name}`);
          lines.push(`  drawGenericGalaxyElement(${p.x}, ${p.y}, ${p.w || 200}, ${p.h || 60}, 10, ${bg}, "${p.title || el.name}", ${text});`);
          break;
        }
      }
      lines.push("");
    });

    lines.push("}");
    return lines.join("\n");
  },

  /**
   * Generate standalone luna_ui_elements.h library
   */
  generateHelperHeader() {
    return `#pragma once
#include <TFT_eSPI.h>
#include <math.h>

extern TFT_eSPI tft;

// ── Uiverse Transaction Card ──
inline void drawTransactionCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, uint16_t iconBg, const char* title, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.fillRoundRect(x + 8, y + 8, 32, h - 16, 6, iconBg);
  tft.setTextColor(0xFFFF, iconBg);
  tft.drawString("$", x + 18, y + 16, 2);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, x + 48, y + 18, 2);
  tft.setTextColor(0x7BEF, bg);
  tft.drawString(">", x + w - 16, y + 16, 2);
}

// ── Uiverse Order Validated Card ──
inline void drawOrderValidatedCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t accent, const char* title, const char* subtitle, uint16_t textCol, uint16_t subCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0xCE79);
  int16_t cx = x + w / 2;
  tft.drawCircle(cx, y + 20, 12, accent);
  tft.setTextColor(accent, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString("V", cx, y + 20, 2);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, cx, y + 46, 2);
  tft.setTextColor(subCol, bg);
  tft.drawString(subtitle, cx, y + 68, 1);
}

// ── Uiverse Push Alert Card (vinodjangid07) ──
inline void drawPushCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t bell, const char* title, const char* subtitle, uint16_t textCol, uint16_t subCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0xCE79);
  tft.fillRoundRect(x + 8, y + 10, 32, 32, 8, 0xFEA0);
  tft.setTextColor(bell, 0xFEA0);
  tft.setTextDatum(MC_DATUM);
  tft.drawString("!", x + 24, y + 26, 2);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, x + 48, y + 14, 2);
  tft.setTextColor(subCol, bg);
  tft.drawString(subtitle, x + 48, y + 36, 1);
}

// ── Uiverse Weather Forecast Card ──
inline void drawWeatherCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* city, const char* temp, const char* cond, uint16_t accent, uint16_t textCol, uint16_t subCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, accent);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(subCol, bg);
  tft.drawString(city, x + 12, y + 10, 1);
  tft.setTextColor(textCol, bg);
  tft.drawString(temp, x + 12, y + 24, 4);
  tft.setTextColor(accent, bg);
  tft.drawString(cond, x + 12, y + 54, 1);
  // Sun icon
  tft.fillCircle(x + w - 32, y + 36, 14, 0xFDA0);
}

// ── Uiverse Music Player Card ──
inline void drawMusicCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* track, const char* artist, uint8_t prog, uint16_t accent, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, accent);
  tft.fillCircle(x + 24, y + 24, 14, accent);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(track, x + 46, y + 12, 2);
  tft.setTextColor(0x9CF3, bg);
  tft.drawString(artist, x + 46, y + 30, 1);
  // Progress bar
  tft.fillRoundRect(x + 12, y + h - 14, w - 24, 4, 2, 0x18E3);
  tft.fillRoundRect(x + 12, y + h - 14, (w - 24) * prog / 100, 4, 2, accent);
}

// ── Uiverse Profile Card ──
inline void drawProfileCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* user, const char* rank, const char* lvl, uint16_t accent, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, accent);
  tft.fillCircle(x + 24, y + h / 2, 16, 0x2124);
  tft.drawCircle(x + 24, y + h / 2, 16, accent);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(user, x + 48, y + 14, 2);
  tft.setTextColor(0x9CF3, bg);
  tft.drawString(rank, x + 48, y + 34, 1);
  tft.drawString(lvl, x + w - 40, y + 14, 1);
}

// ── Uiverse CTA Slide Button (0x-Sarthak) ──
inline void drawCTAButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2 - 8, y + h / 2, 2);
  tft.drawString("->", x + w - 20, y + h / 2, 2);
}

// ── Uiverse Neon Border Button (gharsh) ──
inline void drawNeonBorderButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, 0x0841);
  tft.drawRoundRect(x, y, w, h, r, 0x653F);
  tft.drawRoundRect(x + 1, y + 1, w - 2, h - 2, r, 0x875F);
  tft.setTextColor(textCol, 0x0841);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

// ── Uiverse Flow Gradient Button (adamgiebl) ──
inline void drawFlowButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0x9B5F);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

// ── Uiverse Neumorphic Button (adamgiebl) ──
inline void drawNeumorphicButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0xFFFF);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

// ── Uiverse Scroll Top Button (vinod) ──
inline void drawScrollTopButton(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t bg, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, h / 2, bg);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString("^", x + 18, y + h / 2, 2);
  tft.drawString(label, x + w / 2 + 6, y + h / 2, 2);
}

// ── Uiverse Dot Loader (alexruix) ──
inline void drawDotLoader(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t textCol) {
  tft.fillCircle(x + w / 2, y + 16, 6, 0x9BD5);
  tft.setTextColor(textCol);
  tft.setTextDatum(MC_DATUM);
  tft.drawString("LOADING...", x + w / 2, y + h - 12, 1);
}

// ── Uiverse Coin Loader (Shoh2008) ──
inline void drawCoinLoader(int16_t x, int16_t y, int16_t w, const char* sym, uint16_t bg, uint16_t textCol) {
  tft.fillCircle(x + w / 2, y + w / 2, w / 2 - 2, bg);
  tft.drawCircle(x + w / 2, y + w / 2, w / 2 - 2, 0xB500);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(sym, x + w / 2, y + w / 2, 4);
}

// ── Uiverse Happy Coding Button ──
inline void drawHappyCodingButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

// ── Uiverse Shiny Glass Button ──
inline void drawShinyGlassButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.drawLine(x + 10, y + 2, x + w - 10, y + 2, 0xFFFF);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

// ── Uiverse Download Button (adamgiebl) ──
inline void drawDownloadButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

// ── Uiverse 3D Push Button ──
inline void draw3DPushButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t shadow, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y + 4, w, h - 4, r, shadow);
  tft.fillRoundRect(x, y, w, h - 4, r, bg);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + (h - 4) / 2, 2);
}

// ── Uiverse iOS Switch (adamgiebl) ──
inline void drawIOSSwitch(int16_t x, int16_t y, int16_t w, int16_t h, const char* label, bool checked, uint16_t active, uint16_t inactive, uint16_t textCol) {
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol);
  tft.drawString(label, x, y + (h - 16) / 2, 2);
  int16_t sw = 44, sh = 22;
  int16_t sx = x + w - sw, sy = y + (h - sh) / 2;
  uint16_t track = checked ? active : inactive;
  tft.fillRoundRect(sx, sy, sw, sh, sh / 2, track);
  int16_t thX = checked ? (sx + sw - sh + 2) : (sx + 2);
  tft.fillCircle(thX + (sh - 4) / 2, sy + sh / 2, (sh - 4) / 2, 0xFFFF);
}

// ── Uiverse Sun/Moon Switch ──
inline void drawSunMoonSwitch(int16_t x, int16_t y, int16_t w, int16_t h, const char* label, bool checked, uint16_t textCol) {
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol);
  tft.drawString(label, x, y + (h - 16) / 2, 2);
  int16_t sw = 48, sh = 24;
  int16_t sx = x + w - sw, sy = y + (h - sh) / 2;
  tft.fillRoundRect(sx, sy, sw, sh, sh / 2, checked ? 0x18E3 : 0x3DFE);
  int16_t thX = checked ? (sx + sw - sh + 2) : (sx + 2);
  tft.fillCircle(thX + (sh - 4) / 2, sy + sh / 2, (sh - 4) / 2, 0xFFFF);
}

// ── Uiverse Speaker Switch ──
inline void drawSpeakerSwitch(int16_t x, int16_t y, int16_t w, int16_t h, const char* label, bool checked, uint16_t textCol) {
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol);
  tft.drawString(label, x, y + (h - 16) / 2, 2);
  int16_t sw = 42, sh = 24;
  int16_t sx = x + w - sw, sy = y + (h - sh) / 2;
  tft.fillRoundRect(sx, sy, sw, sh, 8, checked ? 0x637F : 0x4A69);
  tft.setTextColor(0xFFFF, checked ? 0x637F : 0x4A69);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(checked ? "ON" : "OFF", sx + sw / 2, sy + sh / 2, 2);
}

// ── Uiverse Level Up Toast (alexruix) ──
inline void drawLevelUpToast(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* player, const char* level, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0x2649);
  tft.fillCircle(x + 22, y + h / 2, 14, 0x05E5);
  tft.setTextColor(0xFFFF, 0x05E5);
  tft.setTextDatum(MC_DATUM);
  tft.drawString("W", x + 22, y + h / 2, 2);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(player, x + 44, y + 12, 2);
  tft.setTextColor(0x07E0, bg);
  tft.drawString(level, x + 44, y + 30, 2);
}

// ── Uiverse Star Toast ──
inline void drawStarToast(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* title, const char* subtitle, uint16_t star, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, star);
  tft.setTextColor(star, bg);
  tft.drawString("*", x + 14, y + 14, 4);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, x + 44, y + 14, 2);
  tft.setTextColor(0x9CF3, bg);
  tft.drawString(subtitle, x + 44, y + 34, 1);
}

// ── Uiverse Neumorphic Inset Input ──
inline void drawNeumorphicInput(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* text, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0xBDF7);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(TL_DATUM);
  tft.drawString(text, x + 12, y + (h - 16) / 2, 2);
}

// ── Uiverse Cyber Search ──
inline void drawCyberSearch(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* text, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.drawCircle(x + 18, y + h / 2, 5, border);
  tft.drawLine(x + 22, y + h / 2 + 3, x + 26, y + h / 2 + 7, border);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(TL_DATUM);
  tft.drawString(text, x + 34, y + (h - 16) / 2, 2);
}

// ── Generic Galaxy Element Fallback ──
inline void drawGenericGalaxyElement(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* name, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, 0x4BAF);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(name, x + w / 2, y + h / 2, 2);
}

// ── Existing Elements ──
inline void drawGetStartedButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, const char* label, const char* badge, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2 - 12, y + h / 2, 2);
  tft.fillRoundRect(x + w - 30, y + (h - 18) / 2, 18, 18, 4, 0x4B3D);
  tft.setTextColor(0xFFFF, 0x4B3D);
  tft.drawString(badge, x + w - 21, y + h / 2, 1);
}

inline void drawActionDock(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, uint16_t iconCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  int16_t seg = w / 3;
  tft.setTextColor(iconCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString("A", x + seg / 2, y + h / 2, 2);
  tft.drawString("B", x + seg + seg / 2, y + h / 2, 2);
  tft.drawString("C", x + 2 * seg + seg / 2, y + h / 2, 2);
}

inline void drawGlassCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* title, const char* sub, uint16_t textCol, uint16_t subCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, x + 10, y + 10, 2);
  tft.setTextColor(subCol, bg);
  tft.drawString(sub, x + 10, y + 30, 1);
  tft.fillRect(x + 10, y + h - 6, w - 20, 2, border);
}

inline void drawStatCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* label, const char* val, const char* unit, uint16_t accent, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(0x9CF3, bg);
  tft.drawString(label, x + 8, y + 8, 1);
  tft.setTextColor(textCol, bg);
  tft.drawString(val, x + 8, y + 24, 4);
  tft.setTextColor(accent, bg);
  tft.drawString(unit, x + 65, y + 36, 1);
}

inline void drawNotificationCard(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* sender, const char* title, const char* msg, const char* time, uint16_t badge, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.fillRoundRect(x + 8, y + 8, 52, 16, 4, badge);
  tft.setTextColor(0x0000, badge);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(sender, x + 34, y + 16, 1);
  tft.setTextDatum(TR_DATUM);
  tft.setTextColor(0x9CF3, bg);
  tft.drawString(time, x + w - 8, y + 10, 1);
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, x + 8, y + 28, 2);
  tft.setTextColor(0x9CF3, bg);
  tft.drawString(msg, x + 8, y + 46, 1);
}

inline void drawRetroArcadeBox(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t bg, uint16_t border, const char* title, const char* score, uint16_t textCol) {
  tft.fillRect(x, y, w, h, bg);
  tft.drawRect(x, y, w, h, border);
  tft.drawRect(x + 3, y + 3, w - 6, h - 6, border);
  tft.setTextDatum(MC_DATUM);
  tft.setTextColor(textCol, bg);
  tft.drawString(title, x + w / 2, y + 16, 1);
  tft.setTextColor(0xFFFF, bg);
  tft.drawString(score, x + w / 2, y + 38, 2);
}

inline void drawNeonButton(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint16_t bg, uint16_t border, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, r, bg);
  tft.drawRoundRect(x, y, w, h, r, border);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

inline void drawPillButton(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t bg, const char* label, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, h / 2, bg);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

inline void drawRetroButton(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t bg, uint16_t border, const char* label, uint16_t textCol) {
  tft.fillRect(x, y, w, h, bg);
  tft.drawRect(x, y, w, h, border);
  tft.setTextColor(textCol, bg);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(label, x + w / 2, y + h / 2, 2);
}

inline void drawToggleSwitch(int16_t x, int16_t y, int16_t w, int16_t h, const char* label, bool checked, uint16_t active, uint16_t inactive, uint16_t textCol) {
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol);
  tft.drawString(label, x, y + (h - 16) / 2, 2);
  int16_t sw = 40, sh = 20;
  int16_t sx = x + w - sw, sy = y + (h - sh) / 2;
  tft.fillRoundRect(sx, sy, sw, sh, sh / 2, checked ? active : inactive);
  int16_t thX = checked ? (sx + sw - sh + 2) : (sx + 2);
  tft.fillCircle(thX + (sh - 4) / 2, sy + sh / 2, (sh - 4) / 2, 0xFFFF);
}

inline void drawCheckbox(int16_t x, int16_t y, const char* label, bool checked, uint16_t color, uint16_t textCol) {
  tft.drawRoundRect(x, y, 20, 20, 4, color);
  if (checked) {
    tft.fillRoundRect(x + 2, y + 2, 16, 16, 3, color);
  }
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol);
  tft.drawString(label, x + 30, y + 2, 2);
}

inline void drawProgressBar(int16_t x, int16_t y, int16_t w, int16_t h, int16_t r, uint8_t val, const char* label, uint16_t fill, uint16_t bg, uint16_t textCol) {
  tft.setTextDatum(TL_DATUM);
  tft.setTextColor(textCol);
  tft.drawString(label, x, y, 1);
  char buf[8]; sprintf(buf, "%d%%", val);
  tft.setTextDatum(TR_DATUM);
  tft.drawString(buf, x + w, y, 1);
  tft.fillRoundRect(x, y + 16, w, h - 16, r, bg);
  int16_t fillW = (int32_t)(w - 4) * val / 100;
  if (fillW > 0) tft.fillRoundRect(x + 2, y + 18, fillW, h - 20, r > 2 ? r - 2 : 1, fill);
}

inline void drawRadialDial(int16_t x, int16_t y, int16_t w, uint8_t val, const char* label, const char* timeStr, uint16_t arc, uint16_t track, uint16_t textCol) {
  int16_t cx = x + w / 2, cy = y + w / 2, rad = w / 2 - 6;
  tft.drawCircle(cx, cy, rad, track);
  tft.drawCircle(cx, cy, rad - 1, track);
  tft.drawCircle(cx, cy, rad, arc);
  tft.setTextDatum(MC_DATUM);
  tft.setTextColor(0x9CF3);
  tft.drawString(label, cx, cy - 12, 1);
  tft.setTextColor(textCol);
  tft.drawString(timeStr, cx, cy + 10, 4);
}

inline void drawBatteryGauge(int16_t x, int16_t y, uint8_t pct, bool chg, uint16_t col, uint16_t textCol) {
  tft.fillRoundRect(x, y, 120, 26, 13, 0x18E3);
  tft.setTextColor(textCol, 0x18E3);
  tft.setTextDatum(TL_DATUM);
  char buf[16];
  sprintf(buf, "%s%d%%", chg ? "+" : "", pct);
  tft.drawString(buf, x + 10, y + 6, 2);
  tft.drawRoundRect(x + 75, y + 6, 32, 14, 2, col);
  int16_t fillW = (pct * 28) / 100;
  if (fillW > 0) tft.fillRect(x + 77, y + 8, fillW, 10, col);
}

inline void drawAudioWaveform(int16_t x, int16_t y, int16_t w, int16_t h, uint16_t barCol, uint16_t bgCol) {
  tft.fillRoundRect(x, y, w, h, 6, bgCol);
  int heights[] = { 10, 20, 26, 14, 30, 22, 28, 16, 22 };
  int barW = (w - 30) / 9;
  for (int i = 0; i < 9; i++) {
    int curH = heights[i] * (h - 10) / 30;
    tft.fillRoundRect(x + 10 + i * (barW + 2), y + h - 5 - curH, barW, curH, 1, barCol);
  }
}

inline void drawDigitalClock(int16_t x, int16_t y, const char* timeStr, const char* sec, const char* dateStr, uint16_t col, uint16_t dateCol) {
  tft.setTextDatum(MC_DATUM);
  tft.setTextColor(col);
  tft.drawString(timeStr, x + 90, y + 28, 6);
  tft.drawString(sec, x + 160, y + 24, 2);
  tft.setTextColor(dateCol);
  tft.drawString(dateStr, x + 100, y + 58, 2);
}

inline void drawStatusBadge(int16_t x, int16_t y, int16_t w, int16_t h, const char* txt, uint16_t col, uint16_t textCol) {
  tft.fillRoundRect(x, y, w, h, h / 2, col);
  tft.setTextColor(textCol, col);
  tft.setTextDatum(MC_DATUM);
  tft.drawString(txt, x + w / 2, y + h / 2, 2);
}
`;
  }
};
