// Luna Smartwatch Custom Wallpaper - 240x240 RGB565
// Auto-generated by Luna Companion App. Do not edit manually.
#ifndef WALLPAPER_IMAGE_H
#define WALLPAPER_IMAGE_H

#include <pgmspace.h>

#define WALLPAPER_WIDTH  240
#define WALLPAPER_HEIGHT 240
#define WALLPAPER_IS_DEFAULT 1

// Default: solid dark background (1 pixel, will be tiled)
const uint16_t wallpaper_data[1] PROGMEM = { 0x1082 };

#endif
