// Luna Smartwatch Custom Wallpaper - 240x240 RGB565
// Auto-generated by Luna Companion App. Do not edit manually.
#ifndef WALLPAPER_IMAGE_H
#define WALLPAPER_IMAGE_H

#include <pgmspace.h>
#include <Adafruit_GFX.h>

#define WALLPAPER_WIDTH  240
#define WALLPAPER_HEIGHT 240
#define WALLPAPER_IS_DEFAULT 1

// Default: solid dark background (1 pixel, will be tiled)
const uint16_t wallpaper_data[1] PROGMEM = { 0x1082 };

// Custom layout hook for UI designer
inline void drawCustomLayout(GFXcanvas16 &display) {
  display.fillScreen(0x001F); // ST77XX_BLUE
  display.setTextColor(0xFFFF); // ST77XX_WHITE
  display.setTextSize(2);
  display.setCursor(20, 120);
  display.print("Luna Designer UI");
  display.setCursor(20, 150);
  display.print("Active & Ready");
}

#endif
