// Generated custom UI header file. Do not edit.
#ifndef CUSTOM_UI_H
#define CUSTOM_UI_H

#include <Adafruit_GFX.h>
#include "config.h"

// Visual custom drawing function generated by Luna Creative Studio
void drawCustomLayout(GFXcanvas16 &display) {
  display.fillScreen(0x001F);

  // --- Widget: statusbar_653 (statusbar) ---
  display.fillRoundRect(0, 0, 240, 24, 6, ST77XX_WHITE);
  display.drawRoundRect(0, 0, 240, 24, 6, 0x2104);
  // Top Bar Draw
  display.fillRect(0, 0, 240, 24, ST77XX_WHITE);
  display.drawFastHLine(0, 0 + 24 - 1, 240, 0x2104);

}

#endif // CUSTOM_UI_H