#!/usr/bin/env python3
"""
tools/convert_sprite_ai.py
Converts Sprite AI animation export (atlas PNG or ZIP file containing atlas PNG + JSON)
into ESP32-friendly RGB565 PROGMEM arrays for Adafruit GFX / ST7789 display.
"""

import sys
import os
import zipfile
import io
from PIL import Image

def r888_to_565(r, g, b):
    """Convert RGB888 tuple to 16-bit RGB565 integer."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def convert_sprite_ai(zip_or_png_path, output_header_path, target_w=240, target_h=240):
    print(f"[CONVERT] Loading asset from: {zip_or_png_path}")
    
    if zip_or_png_path.endswith('.zip'):
        with zipfile.ZipFile(zip_or_png_path, 'r') as z:
            png_name = None
            for fname in z.namelist():
                if fname.endswith('.png'):
                    png_name = fname
                    break
            if not png_name:
                raise ValueError("No PNG file found inside ZIP archive")
            print(f"[CONVERT] Found PNG in zip: {png_name}")
            img_bytes = z.read(png_name)
            img = Image.open(io.BytesIO(img_bytes)).convert('RGBA')
    else:
        img = Image.open(zip_or_png_path).convert('RGBA')
        
    width, height = img.size
    print(f"[CONVERT] Image size: {width}x{height}")
    
    # Calculate number of 256x256 frames assuming vertical or horizontal layout
    frame_size = 256
    if width == frame_size:
        frame_count = height // frame_size
    elif height == frame_size:
        frame_count = width // frame_size
    else:
        # Default to 4 frames if 256x1024 layout
        frame_count = height // frame_size if height >= frame_size else 1

    print(f"[CONVERT] Detected {frame_count} frames of {frame_size}x{frame_size}")
    
    frame_array_names = []
    header_content = []
    
    header_content.append("// Automatically generated by tools/convert_sprite_ai.py - DO NOT MODIFY DIRECTLY")
    header_content.append("#ifndef SPRITE_AI_DATA_H")
    header_content.append("#define SPRITE_AI_DATA_H")
    header_content.append("")
    header_content.append("#include <pgmspace.h>")
    header_content.append("#include <stdint.h>")
    header_content.append("")
    header_content.append(f"#define SPRITE_AI_FRAME_WIDTH  {target_w}")
    header_content.append(f"#define SPRITE_AI_FRAME_HEIGHT {target_h}")
    header_content.append(f"#define SPRITE_AI_FRAME_COUNT  {frame_count}")
    header_content.append("#define SPRITE_AI_DEFAULT_FPS  8")
    header_content.append("")

    for i in range(frame_count):
        if width == frame_size:
            crop_box = (0, i * frame_size, frame_size, (i + 1) * frame_size)
        else:
            crop_box = (i * frame_size, 0, (i + 1) * frame_size, frame_size)
            
        frame_img = img.crop(crop_box)
        if (target_w, target_h) != (frame_size, frame_size):
            frame_img = frame_img.resize((target_w, target_h), Image.Resampling.LANCZOS)
            
        array_name = f"luna_sprite_ai_frame_{i:02d}"
        frame_array_names.append(array_name)
        
        pixels = list(frame_img.getdata())
        
        header_content.append(f"const uint16_t {array_name}[{target_w * target_h}] PROGMEM = {{")
        
        line_buffer = []
        for idx, (r, g, b, a) in enumerate(pixels):
            # Alpha check: if fully transparent (a==0), set to black 0x0000
            if a == 0:
                val = 0x0000
            else:
                val = r888_to_565(r, g, b)
            line_buffer.append(f"0x{val:04X}")
            
            if len(line_buffer) == 12:
                header_content.append("  " + ", ".join(line_buffer) + ",")
                line_buffer = []
                
        if line_buffer:
            header_content.append("  " + ", ".join(line_buffer))
            
        header_content.append("};")
        header_content.append("")
        print(f"[CONVERT] Frame {i:02d} processed ({target_w}x{target_h}).")
        
    header_content.append("// Frame table for direct indexing")
    header_content.append(f"const uint16_t* const luna_sprite_ai_frames[{frame_count}] PROGMEM = {{")
    for name in frame_array_names:
        header_content.append(f"  {name},")
    header_content.append("};")
    header_content.append("")
    header_content.append("#endif // SPRITE_AI_DATA_H")
    
    os.makedirs(os.path.dirname(os.path.abspath(output_header_path)), exist_ok=True)
    with open(output_header_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header_content) + "\n")
        
    total_bytes = frame_count * target_w * target_h * 2
    print(f"[CONVERT] Successfully wrote {output_header_path}")
    print(f"[CONVERT] Total PROGMEM size: {total_bytes} bytes ({total_bytes / 1024:.2f} KB)")

if __name__ == "__main__":
    src_path = sys.argv[1] if len(sys.argv) > 1 else r"W:\Mr.mario\sprite-animation-256x256-4f-atlas.zip"
    out_path = sys.argv[2] if len(sys.argv) > 2 else r"W:\Mr.mario\1.69 Luna Firmware\sprite_ai_data.h"
    convert_sprite_ai(src_path, out_path)
