#!/usr/bin/env python3
"""
tools/convert_sprite_ai.py
Converts multiple Sprite AI animation ZIP files into ESP32 RGB565 PROGMEM arrays.
Forces dark background pixels (max(R,G,B) <= 20) to pure black 0x0000 so the animation
box seamlessly merges with the TFT_BLACK screen background with zero visible edges.
"""

import sys
import os
import zipfile
import io
from PIL import Image

def r888_to_565(r, g, b):
    """Convert RGB888 tuple to 16-bit RGB565 integer."""
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)

def convert_multiple_sprite_ai(zip_paths, output_header_path, target_w=240, target_h=240, dark_threshold=20):
    header_content = []
    header_content.append("// Automatically generated by tools/convert_sprite_ai.py - DO NOT MODIFY DIRECTLY")
    header_content.append("#ifndef SPRITE_AI_DATA_H")
    header_content.append("#define SPRITE_AI_DATA_H")
    header_content.append("")
    header_content.append("#include <pgmspace.h>")
    header_content.append("#include <stdint.h>")
    header_content.append("")
    header_content.append(f"#define SPRITE_AI_FRAME_WIDTH      {target_w}")
    header_content.append(f"#define SPRITE_AI_FRAME_HEIGHT     {target_h}")
    header_content.append(f"#define SPRITE_AI_ANIMATION_COUNT  {len(zip_paths)}")
    header_content.append("#define SPRITE_AI_FRAME_COUNT      4")
    header_content.append("#define SPRITE_AI_DEFAULT_FPS      8")
    header_content.append("")

    for anim_idx, zip_path in enumerate(zip_paths):
        print(f"[CONVERT] Loading Anim #{anim_idx} from: {zip_path}")
        with zipfile.ZipFile(zip_path, 'r') as z:
            png_name = None
            for fname in z.namelist():
                if fname.endswith('.png'):
                    png_name = fname
                    break
            if not png_name:
                raise ValueError(f"No PNG found inside {zip_path}")
            img_bytes = z.read(png_name)
            img = Image.open(io.BytesIO(img_bytes)).convert('RGBA')

        width, height = img.size
        frame_size = 256
        frame_count = height // frame_size if width == frame_size else width // frame_size
        if frame_count > 4:
            frame_count = 4

        for f_idx in range(frame_count):
            if width == frame_size:
                crop_box = (0, f_idx * frame_size, frame_size, (f_idx + 1) * frame_size)
            else:
                crop_box = (f_idx * frame_size, 0, (f_idx + 1) * frame_size, frame_size)

            frame_img = img.crop(crop_box)
            if (target_w, target_h) != (frame_size, frame_size):
                frame_img = frame_img.resize((target_w, target_h), Image.Resampling.LANCZOS)

            array_name = f"luna_sprite_ai_anim{anim_idx}_frame_{f_idx:02d}"

            pixels = list(frame_img.get_flattened_data() if hasattr(frame_img, 'get_flattened_data') else frame_img.getdata())
            header_content.append(f"const uint16_t {array_name}[{target_w * target_h}] PROGMEM = {{")

            line_buffer = []
            black_count = 0
            for idx, (r, g, b, a) in enumerate(pixels):
                # If transparent or near-black background pixel, force to pure black 0x0000
                if a == 0 or (r <= dark_threshold and g <= dark_threshold and b <= dark_threshold):
                    val = 0x0000
                    black_count += 1
                else:
                    val = r888_to_565(r, g, b)
                line_buffer.append(f"0x{val:04X}")

                if len(line_buffer) == 12:
                    header_content.append("  " + ", ".join(line_buffer) + ",")
                    line_buffer = []

            if line_buffer:
                header_content.append("  " + ", ".join(line_buffer))

            header_content.append("};")
            header_content.append("")
            pct_black = (black_count / (target_w * target_h)) * 100.0
            print(f"[CONVERT] Anim #{anim_idx} Frame {f_idx:02d} processed ({target_w}x{target_h}): {pct_black:.1f}% forced to pure black 0x0000.")

    # Helper function for safe, zero-indirection frame retrieval
    header_content.append("// Safe direct lookup function returning PROGMEM pointer without indirect pointer arrays")
    header_content.append("inline const uint16_t* getSpriteAiFrame(int animIdx, int frameIdx) {")
    header_content.append("  if (animIdx < 0 || animIdx >= SPRITE_AI_ANIMATION_COUNT) animIdx = 0;")
    header_content.append("  if (frameIdx < 0 || frameIdx >= SPRITE_AI_FRAME_COUNT) frameIdx = 0;")
    header_content.append("  switch (animIdx) {")
    for a_idx in range(len(zip_paths)):
        header_content.append(f"    case {a_idx}:")
        header_content.append("      switch (frameIdx) {")
        header_content.append(f"        case 0: return luna_sprite_ai_anim{a_idx}_frame_00;")
        header_content.append(f"        case 1: return luna_sprite_ai_anim{a_idx}_frame_01;")
        header_content.append(f"        case 2: return luna_sprite_ai_anim{a_idx}_frame_02;")
        header_content.append(f"        case 3: return luna_sprite_ai_anim{a_idx}_frame_03;")
        header_content.append("      }")
        header_content.append("      break;")
    header_content.append("  }")
    header_content.append("  return luna_sprite_ai_anim0_frame_00;")
    header_content.append("}")
    header_content.append("")
    header_content.append("#endif // SPRITE_AI_DATA_H")

    os.makedirs(os.path.dirname(os.path.abspath(output_header_path)), exist_ok=True)
    with open(output_header_path, "w", encoding="utf-8") as f:
        f.write("\n".join(header_content) + "\n")

    total_bytes = len(zip_paths) * 4 * target_w * target_h * 2
    print(f"[CONVERT] Successfully wrote {output_header_path}")
    print(f"[CONVERT] Total PROGMEM size for {len(zip_paths)} animations ({target_w}x{target_h}): {total_bytes} bytes ({total_bytes / 1024:.2f} KB / {total_bytes / (1024*1024):.2f} MB)")

if __name__ == "__main__":
    zips = [
        r"W:\Mr.mario\sprite-animation-256x256-4f-atlas.zip",
        r"W:\Mr.mario\sprite-animation-256x256-4f-atlas (1).zip",
        r"W:\Mr.mario\sprite-animation-256x256-4f-atlas (2).zip",
        r"W:\Mr.mario\sprite-256x256px-4f-atlas.zip",
        r"W:\Mr.mario\sprite-animation-256x256-4f-addtlas (1).zip",
        r"W:\Mr.mario\sprite-animation-256x256-4f-atlddas.zip"
    ]
    out_h = r"W:\Mr.mario\1.69 Luna Firmware\sprite_ai_data.h"
    convert_multiple_sprite_ai(zips, out_h, target_w=240, target_h=240, dark_threshold=20)
