// ==========================================================================
// Generated by Luna Display Studio for ESP32-S3 1.69" (240x280 ST7789)
// ==========================================================================
#include "luna_gfx_compat.h"
#include "luna_ui_elements.h"

extern TFT_eSPI tft;

void drawGeneratedScreen() {
  tft.fillScreen(0x0863);

  // ── Element 1: digital_clock (Digital Clock) ──
  drawDigitalClock(20, 20, "10:45", "WED, SEP 9", 0x079F, 0x9517);

  // ── Element 2: card_glass (Glass Card) ──
  drawGlassCard(20, 95, 208, 80, 14, 0x1947, 0x079F, "Status", "System online • v2.0", 0xFFFF);

  // ── Element 3: uiv_btn_happy_coding (Happy Coding Button) ──
  drawHappyCodingButton(20, 205, 190, 50, 0xEF9F, 0x537F, "Happy Coding!", 0x537F);

}